INSERT INTO [Jedis] ([Nom], [IsSith], [Image]) VALUES ('Obi Wan Kenobi', 0, 'img/default.png'),
('Yoda', 0, 'img/default.png'),
('Mace Windu', 0, 'img/default.png'),
('Aayla Secura', 0, 'img/default.png'),
('Shaak Ti', 0, 'img/default.png'),
('Plo Koon', 0, 'img/default.png'),
('Kit Fist', 0, 'img/default.png'),
('Qui Gon Jinn', 0, 'img/default.png'),
('Luke Skywalker', 0, 'img/default.png'),
('Anakin Skywalker', 1, 'img/default.png'),
('Rey Skywalker', 0, 'img/default.png'),
('Dark Sidious', 1, 'img/default.png'),
('Dark Vador', 1, 'img/default.png'),
('Grivious', 1, 'img/default.png'),
('Dark Maul', 1, 'img/default.png'),
('Dooku', 1, 'img/default.png'),
('Kylo Ren', 1, 'img/default.png'),
('Dark Revan', 1, 'img/default.png');

INSERT INTO [Stades] ([Nom], [NbPlaces], [Image]) VALUES ('Coruscant', 1000000,'img/planet.png'),
('Kamino',100000,'img/planet.png'),
('Naboo',10000,'img/planet.png'),
('Tatooine',666,'img/planet.png'),
('Dagobah',4,'img/planet.png')